language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t chanmheric/docker-react -f Dockerfile.dev .

script:
    - docker run ie CI=true chanmheric/docker-react npm run test -- --coverage
